### ISSUE TITLE
3. Aggiunta badge GitHub Actions

### ISSUE THREAD

**Issue by SaraPadovano** [softeng2223-inf-uniba/progetto2223-yao#4]
Modificare il file markdown README.md per aggiungere il badge di **GitHub Actions**, seguendo le indicazioni contenute nella Guida per lo studente.md

**Comment by gnavolio** [comment]
Si riesco a visualizzarlo 👍

**Comment by Kamil3434** [comment]
Aprendo il file le vedo, dovrebbe essere tutto ok 💯
