### ISSUE TITLE
6. Creazione regolamento gruppo.

### ISSUE THREAD

**Issue by Giuliapanfilo** [softeng2223-inf-uniba/progetto2223-yao#5]
Creare il file markdown CODE_OF_CONDUCT.md. Il file esplicita le regole di comportamento comuni al gruppo, di comune accordo.

**Comment by Kamil3434** [comment]
Ho tradotto il file del regolamento, nel branch regolamento potete vedere il file CODE_OF_CONDUCT, se avete altre regole da aggiungere provvederò
@Giuliapanfilo @gnavolio @SaraPadovano @raffaelepapeo

**Comment by raffaelepapeo** [comment]
> Ho tradotto il file del regolamento, nel branch regolamento potete vedere il file CODE_OF_CONDUCT, se avete altre regole da aggiungere provvederò
> @Giuliapanfilo @gnavolio @SaraPadovano @raffaelepapeo

Secondo me va aggiunto un punto in cui viene stabilito che la review e l'approvazione devono essere eseguite da 3 membri del team.

**Comment by SaraPadovano** [comment]
Più che scrivere "Migliorare la velocita' del team e' piu' importante di migliorare la mia", io scriverei "I componenti del team devono andare allo stesso passo".

**Comment by gnavolio** [comment]
Secondo me potremmo aggiungere la seguente regola nel campo "partecipazione al progetto del team":
Farò notare eventuali errori o "sbavature", sempre con rispetto del lavoro altrui.

**Comment by Giuliapanfilo** [comment]
Ok, provvedo io @gnavolio @SaraPadovano @Kamil3434 @raffaelepapeo
