### ISSUE TITLE
7. Riportare la biografia e principali contributi di Yao

### ISSUE THREAD

**Issue by gnavolio** [softeng2223-inf-uniba/progetto2223-yao#6]
Creare il file markdown ISPIRATORE.md nella directory docs per riportare biografia e principali contributi del personaggio a cui il gruppo si è ispirato per il nome. Il testo deve essere in lingua italiana e contenere non meno di 500 caratteri e 100 parole.

**Comment by SaraPadovano** [comment]
Ho fatto la prima commit e push del file ISPIRATORE.md. Secondo voi @gnavolio @raffaelepapeo @Kamil3434 @Giuliapanfilo , quello che ho scritto va bene? Posso continuare?

**Comment by raffaelepapeo** [comment]
> Ho fatto la prima commit e push del file ISPIRATORE.md. Secondo voi @gnavolio @raffaelepapeo @Kamil3434 @Giuliapanfilo , quello che ho scritto va bene? Posso continuare?

Si, secondo me va bene. Puoi continuare così

**Comment by gnavolio** [comment]
> Ho fatto la prima commit e push del file ISPIRATORE.md. Secondo voi @gnavolio @raffaelepapeo @Kamil3434 @Giuliapanfilo , quello che ho scritto va bene? Posso continuare?

Per quanto mi riguarda, puoi tranquillamente continuare.

**Comment by SaraPadovano** [comment]
@raffaelepapeo @gnavolio @Kamil3434 @Giuliapanfilo ho finito la trasposizione della biografia di Yao e dei suoi contributi. Secondo voi va bene?

**Comment by gnavolio** [comment]
Si secondo me va bene, però magari proverei ad aggiungere parole in grassetto ed in corsivo, per rendere più esplicativo il testo.

**Comment by Kamil3434** [comment]
Il contenuto penso sia più che sufficiente, migliora lo stile dividendolo meglio in paragrafi per migliorare la lettura
