### ISSUE TITLE
5. Personalizzazione della guida

### ISSUE THREAD

**Issue by raffaelepapeo** [softeng2223-inf-uniba/progetto2223-yao#7]
Modificare il file markdown studente.md personalizzando le figure in cui compare un nome di repository diverso dal proprio, oppure uno username o immagine di profilo diverso da quello dei componenti del gruppo.

**Comment by raffaelepapeo** [comment]
Ho modificato la prima parte della guida per lo studente.md personalizzando le immagini e le modifiche sono visibili correttamente

**Comment by Kamil3434** [comment]
Ho controllato il file, le modifiche delle immagini sono presenti
